import = ["util/convert.toml"]

[project]
name = "mkcss"
version = "0.2.0"

[tasks.build]
info = "Build binaries"
script = [
   "maid clean -q",
   "cargo build --release", 
   "mv target/release/mkcss bin/mkcss",
]

[tasks.build.cache]
path = "src"
target = ["bin/mkcss"]

[tasks]
clean = { info = "Clean binary files", script = ["rimraf bin", "mkdir bin"] }
install = { info = "Move binary file", script = ["sudo cp bin/mkcss /usr/local/bin", "echo Copied binary!"], depends = ["build"] }
