pub const SANS: &str = r#"font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji""#;
pub const SERIF: &str = r#"font-family: ui-serif, Georgia, Cambria, "Times New Roman", Times, serif;"#;
pub const MONO: &str = r#"font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;"#;

pub const STYLES: [(&str, &str); 273] = [
    ("text-xs", "font-size: 10px"),
    ("text-sm", "font-size: 12px"),
    ("text-md", "font-size: 14px"),
    ("text-lg", "font-size: 18px"),
    ("text-xl", "font-size: 24px"),
    ("text-left", "text-align: left"),
    ("text-center", "text-align: center"),
    ("text-right", "text-align: right"),
    ("text-justify", "text-align: justify"),
    ("text-start", "text-align: start"),
    ("text-end", "text-align: end"),
    ("font-thin", "font-weight: 100"),
    ("font-extralight", "font-weight: 200"),
    ("font-light", "font-weight: 300"),
    ("font-normal", "font-weight: 400"),
    ("font-medium", "font-weight: 500"),
    ("font-semibold", "font-weight: 600"),
    ("font-bold", "font-weight: 700"),
    ("font-extrabold", "font-weight: 800"),
    ("font-black", "font-weight: 900"),
    ("rounded-none", "border-radius: 0px"),
    ("rounded-sm", "border-radius: 0.125rem"),
    ("rounded", "border-radius: 0.25rem"),
    ("rounded-md", "border-radius: 0.375rem"),
    ("rounded-lg", "border-radius: 0.5rem"),
    ("rounded-xl", "border-radius: 0.75rem"),
    ("rounded-2xl", "border-radius: 1rem"),
    ("rounded-3xl", "border-radius: 1.5rem"),
    ("rounded-full", "border-radius: 9999px"),
    ("rounded-s-none", "border-start-start-radius: 0px"),
    ("border-end-start-radius:", "0px"),
    ("rounded-s-sm", "border-start-start-radius: 0.125rem"),
    ("border-end-start-radius:", "0.125rem"),
    ("rounded-s", "border-start-start-radius: 0.25rem"),
    ("border-end-start-radius:", "0.25rem"),
    ("rounded-s-md", "border-start-start-radius: 0.375rem"),
    ("border-end-start-radius:", "0.375rem"),
    ("rounded-s-lg", "border-start-start-radius: 0.5rem"),
    ("border-end-start-radius:", "0.5rem"),
    ("rounded-s-xl", "border-start-start-radius: 0.75rem"),
    ("border-end-start-radius:", "0.75rem"),
    ("rounded-s-2xl", "border-start-start-radius: 1rem"),
    ("border-end-start-radius:", "1rem"),
    ("rounded-s-3xl", "border-start-start-radius: 1.5rem"),
    ("border-end-start-radius:", "1.5rem"),
    ("rounded-s-full", "border-start-start-radius: 9999px"),
    ("border-end-start-radius:", "9999px"),
    ("rounded-e-none", "border-start-end-radius: 0px"),
    ("border-end-end-radius:", "0px"),
    ("rounded-e-sm", "border-start-end-radius: 0.125rem"),
    ("border-end-end-radius:", "0.125rem"),
    ("rounded-e", "border-start-end-radius: 0.25rem"),
    ("border-end-end-radius:", "0.25rem"),
    ("rounded-e-md", "border-start-end-radius: 0.375rem"),
    ("border-end-end-radius:", "0.375rem"),
    ("rounded-e-lg", "border-start-end-radius: 0.5rem"),
    ("border-end-end-radius:", "0.5rem"),
    ("rounded-e-xl", "border-start-end-radius: 0.75rem"),
    ("border-end-end-radius:", "0.75rem"),
    ("rounded-e-2xl", "border-start-end-radius: 1rem"),
    ("border-end-end-radius:", "1rem"),
    ("rounded-e-3xl", "border-start-end-radius: 1.5rem"),
    ("border-end-end-radius:", "1.5rem"),
    ("rounded-e-full", "border-start-end-radius: 9999px"),
    ("border-end-end-radius:", "9999px"),
    ("rounded-t-none", "border-top-left-radius: 0px"),
    ("border-top-right-radius:", "0px"),
    ("rounded-t-sm", "border-top-left-radius: 0.125rem"),
    ("border-top-right-radius:", "0.125rem"),
    ("rounded-t", "border-top-left-radius: 0.25rem"),
    ("border-top-right-radius:", "0.25rem"),
    ("rounded-t-md", "border-top-left-radius: 0.375rem"),
    ("border-top-right-radius:", "0.375rem"),
    ("rounded-t-lg", "border-top-left-radius: 0.5rem"),
    ("border-top-right-radius:", "0.5rem"),
    ("rounded-t-xl", "border-top-left-radius: 0.75rem"),
    ("border-top-right-radius:", "0.75rem"),
    ("rounded-t-2xl", "border-top-left-radius: 1rem"),
    ("border-top-right-radius:", "1rem"),
    ("rounded-t-3xl", "border-top-left-radius: 1.5rem"),
    ("border-top-right-radius:", "1.5rem"),
    ("rounded-t-full", "border-top-left-radius: 9999px"),
    ("border-top-right-radius:", "9999px"),
    ("rounded-r-none", "border-top-right-radius: 0px"),
    ("border-bottom-right-radius:", "0px"),
    ("rounded-r-sm", "border-top-right-radius: 0.125rem"),
    ("border-bottom-right-radius:", "0.125rem"),
    ("rounded-r", "border-top-right-radius: 0.25rem"),
    ("border-bottom-right-radius:", "0.25rem"),
    ("rounded-r-md", "border-top-right-radius: 0.375rem"),
    ("border-bottom-right-radius:", "0.375rem"),
    ("rounded-r-lg", "border-top-right-radius: 0.5rem"),
    ("border-bottom-right-radius:", "0.5rem"),
    ("rounded-r-xl", "border-top-right-radius: 0.75rem"),
    ("border-bottom-right-radius:", "0.75rem"),
    ("rounded-r-2xl", "border-top-right-radius: 1rem"),
    ("border-bottom-right-radius:", "1rem"),
    ("rounded-r-3xl", "border-top-right-radius: 1.5rem"),
    ("border-bottom-right-radius:", "1.5rem"),
    ("rounded-r-full", "border-top-right-radius: 9999px"),
    ("border-bottom-right-radius:", "9999px"),
    ("rounded-b-none", "border-bottom-right-radius: 0px"),
    ("border-bottom-left-radius:", "0px"),
    ("rounded-b-sm", "border-bottom-right-radius: 0.125rem"),
    ("border-bottom-left-radius:", "0.125rem"),
    ("rounded-b", "border-bottom-right-radius: 0.25rem"),
    ("border-bottom-left-radius:", "0.25rem"),
    ("rounded-b-md", "border-bottom-right-radius: 0.375rem"),
    ("border-bottom-left-radius:", "0.375rem"),
    ("rounded-b-lg", "border-bottom-right-radius: 0.5rem"),
    ("border-bottom-left-radius:", "0.5rem"),
    ("rounded-b-xl", "border-bottom-right-radius: 0.75rem"),
    ("border-bottom-left-radius:", "0.75rem"),
    ("rounded-b-2xl", "border-bottom-right-radius: 1rem"),
    ("border-bottom-left-radius:", "1rem"),
    ("rounded-b-3xl", "border-bottom-right-radius: 1.5rem"),
    ("border-bottom-left-radius:", "1.5rem"),
    ("rounded-b-full", "border-bottom-right-radius: 9999px"),
    ("border-bottom-left-radius:", "9999px"),
    ("rounded-l-none", "border-top-left-radius: 0px"),
    ("border-bottom-left-radius:", "0px"),
    ("rounded-l-sm", "border-top-left-radius: 0.125rem"),
    ("border-bottom-left-radius:", "0.125rem"),
    ("rounded-l", "border-top-left-radius: 0.25rem"),
    ("border-bottom-left-radius:", "0.25rem"),
    ("rounded-l-md", "border-top-left-radius: 0.375rem"),
    ("border-bottom-left-radius:", "0.375rem"),
    ("rounded-l-lg", "border-top-left-radius: 0.5rem"),
    ("border-bottom-left-radius:", "0.5rem"),
    ("rounded-l-xl", "border-top-left-radius: 0.75rem"),
    ("border-bottom-left-radius:", "0.75rem"),
    ("rounded-l-2xl", "border-top-left-radius: 1rem"),
    ("border-bottom-left-radius:", "1rem"),
    ("rounded-l-3xl", "border-top-left-radius: 1.5rem"),
    ("border-bottom-left-radius:", "1.5rem"),
    ("rounded-l-full", "border-top-left-radius: 9999px"),
    ("border-bottom-left-radius:", "9999px"),
    ("rounded-ss-none", "border-start-start-radius: 0px"),
    ("rounded-ss-sm", "border-start-start-radius: 0.125rem"),
    ("rounded-ss", "border-start-start-radius: 0.25rem"),
    ("rounded-ss-md", "border-start-start-radius: 0.375rem"),
    ("rounded-ss-lg", "border-start-start-radius: 0.5rem"),
    ("rounded-ss-xl", "border-start-start-radius: 0.75rem"),
    ("rounded-ss-2xl", "border-start-start-radius: 1rem"),
    ("rounded-ss-3xl", "border-start-start-radius: 1.5rem"),
    ("rounded-ss-full", "border-start-start-radius: 9999px"),
    ("rounded-se-none", "border-start-end-radius: 0px"),
    ("rounded-se-sm", "border-start-end-radius: 0.125rem"),
    ("rounded-se", "border-start-end-radius: 0.25rem"),
    ("rounded-se-md", "border-start-end-radius: 0.375rem"),
    ("rounded-se-lg", "border-start-end-radius: 0.5rem"),
    ("rounded-se-xl", "border-start-end-radius: 0.75rem"),
    ("rounded-se-2xl", "border-start-end-radius: 1rem"),
    ("rounded-se-3xl", "border-start-end-radius: 1.5rem"),
    ("rounded-se-full", "border-start-end-radius: 9999px"),
    ("rounded-ee-none", "border-end-end-radius: 0px"),
    ("rounded-ee-sm", "border-end-end-radius: 0.125rem"),
    ("rounded-ee", "border-end-end-radius: 0.25rem"),
    ("rounded-ee-md", "border-end-end-radius: 0.375rem"),
    ("rounded-ee-lg", "border-end-end-radius: 0.5rem"),
    ("rounded-ee-xl", "border-end-end-radius: 0.75rem"),
    ("rounded-ee-2xl", "border-end-end-radius: 1rem"),
    ("rounded-ee-3xl", "border-end-end-radius: 1.5rem"),
    ("rounded-ee-full", "border-end-end-radius: 9999px"),
    ("rounded-es-none", "border-end-start-radius: 0px"),
    ("rounded-es-sm", "border-end-start-radius: 0.125rem"),
    ("rounded-es", "border-end-start-radius: 0.25rem"),
    ("rounded-es-md", "border-end-start-radius: 0.375rem"),
    ("rounded-es-lg", "border-end-start-radius: 0.5rem"),
    ("rounded-es-xl", "border-end-start-radius: 0.75rem"),
    ("rounded-es-2xl", "border-end-start-radius: 1rem"),
    ("rounded-es-3xl", "border-end-start-radius: 1.5rem"),
    ("rounded-es-full", "border-end-start-radius: 9999px"),
    ("rounded-tl-none", "border-top-left-radius: 0px"),
    ("rounded-tl-sm", "border-top-left-radius: 0.125rem"),
    ("rounded-tl", "border-top-left-radius: 0.25rem"),
    ("rounded-tl-md", "border-top-left-radius: 0.375rem"),
    ("rounded-tl-lg", "border-top-left-radius: 0.5rem"),
    ("rounded-tl-xl", "border-top-left-radius: 0.75rem"),
    ("rounded-tl-2xl", "border-top-left-radius: 1rem"),
    ("rounded-tl-3xl", "border-top-left-radius: 1.5rem"),
    ("rounded-tl-full", "border-top-left-radius: 9999px"),
    ("rounded-tr-none", "border-top-right-radius: 0px"),
    ("rounded-tr-sm", "border-top-right-radius: 0.125rem"),
    ("rounded-tr", "border-top-right-radius: 0.25rem"),
    ("rounded-tr-md", "border-top-right-radius: 0.375rem"),
    ("rounded-tr-lg", "border-top-right-radius: 0.5rem"),
    ("rounded-tr-xl", "border-top-right-radius: 0.75rem"),
    ("rounded-tr-2xl", "border-top-right-radius: 1rem"),
    ("rounded-tr-3xl", "border-top-right-radius: 1.5rem"),
    ("rounded-tr-full", "border-top-right-radius: 9999px"),
    ("rounded-br-none", "border-bottom-right-radius: 0px"),
    ("rounded-br-sm", "border-bottom-right-radius: 0.125rem"),
    ("rounded-br", "border-bottom-right-radius: 0.25rem"),
    ("rounded-br-md", "border-bottom-right-radius: 0.375rem"),
    ("rounded-br-lg", "border-bottom-right-radius: 0.5rem"),
    ("rounded-br-xl", "border-bottom-right-radius: 0.75rem"),
    ("rounded-br-2xl", "border-bottom-right-radius: 1rem"),
    ("rounded-br-3xl", "border-bottom-right-radius: 1.5rem"),
    ("rounded-br-full", "border-bottom-right-radius: 9999px"),
    ("rounded-bl-none", "border-bottom-left-radius: 0px"),
    ("rounded-bl-sm", "border-bottom-left-radius: 0.125rem"),
    ("rounded-bl", "border-bottom-left-radius: 0.25rem"),
    ("rounded-bl-md", "border-bottom-left-radius: 0.375rem"),
    ("rounded-bl-lg", "border-bottom-left-radius: 0.5rem"),
    ("rounded-bl-xl", "border-bottom-left-radius: 0.75rem"),
    ("rounded-bl-2xl", "border-bottom-left-radius: 1rem"),
    ("rounded-bl-3xl", "border-bottom-left-radius: 1.5rem"),
    ("rounded-bl-full", "border-bottom-left-radius: 9999px"),
    ("border", "border-style: solid; border-width: 1px"),
    ("border-0", "border-width: 0px"),
    ("border-2", "border-width: 2px"),
    ("border-4", "border-width: 4px"),
    ("border-8", "border-width: 8px"),
    ("border-x-0", "border-left-width: 0px"),
    ("border-right-width:", "0px"),
    ("border-x-2", "border-left-width: 2px"),
    ("border-right-width:", "2px"),
    ("border-x-4", "border-left-width: 4px"),
    ("border-right-width:", "4px"),
    ("border-x-8", "border-left-width: 8px"),
    ("border-right-width:", "8px"),
    ("border-x", "border-left-width: 1px"),
    ("border-right-width:", "1px"),
    ("border-y-0", "border-top-width: 0px"),
    ("border-bottom-width:", "0px"),
    ("border-y-2", "border-top-width: 2px"),
    ("border-bottom-width:", "2px"),
    ("border-y-4", "border-top-width: 4px"),
    ("border-bottom-width:", "4px"),
    ("border-y-8", "border-top-width: 8px"),
    ("border-bottom-width:", "8px"),
    ("border-y", "border-top-width: 1px"),
    ("border-bottom-width:", "1px"),
    ("border-s-0", "border-inline-start-width: 0px"),
    ("border-s-2", "border-inline-start-width: 2px"),
    ("border-s-4", "border-inline-start-width: 4px"),
    ("border-s-8", "border-inline-start-width: 8px"),
    ("border-s", "border-inline-start-width: 1px"),
    ("border-e-0", "border-inline-end-width: 0px"),
    ("border-e-2", "border-inline-end-width: 2px"),
    ("border-e-4", "border-inline-end-width: 4px"),
    ("border-e-8", "border-inline-end-width: 8px"),
    ("border-e", "border-inline-end-width: 1px"),
    ("border-t-0", "border-top-width: 0px"),
    ("border-t-2", "border-top-width: 2px"),
    ("border-t-4", "border-top-width: 4px"),
    ("border-t-8", "border-top-width: 8px"),
    ("border-t", "border-top-width: 1px"),
    ("border-r-0", "border-right-width: 0px"),
    ("border-r-2", "border-right-width: 2px"),
    ("border-r-4", "border-right-width: 4px"),
    ("border-r-8", "border-right-width: 8px"),
    ("border-r", "border-right-width: 1px"),
    ("border-b-0", "border-bottom-width: 0px"),
    ("border-b-2", "border-bottom-width: 2px"),
    ("border-b-4", "border-bottom-width: 4px"),
    ("border-b-8", "border-bottom-width: 8px"),
    ("border-b", "border-bottom-width: 1px"),
    ("border-l-0", "border-left-width: 0px"),
    ("border-l-2", "border-left-width: 2px"),
    ("border-l-4", "border-left-width: 4px"),
    ("border-l-8", "border-left-width: 8px"),
    ("border-l", "border-left-width: 1px"),
    ("border-solid", "border-style: solid"),
    ("border-dashed", "border-style: dashed"),
    ("border-dotted", "border-style: dotted"),
    ("border-double", "border-style: double"),
    ("border-hidden", "border-style: hidden"),
    ("border-none", "border-style: none"),
    ("font-sans", SANS),
    ("font-serif", SERIF),
    ("font-mono", MONO),
];

pub const CONTROL_STYLES: [(&str, &str); 14] = [
    ("m", "margin"),
    ("mt", "margin-top"),
    ("mr", "margin-right"),
    ("mb", "margin-bottom"),
    ("ml", "margin-left"),
    ("mx", "margin-left margin-right"),
    ("my", "margin-top margin-bottom"),
    ("p", "padding"),
    ("pt", "padding-top"),
    ("pr", "padding-right"),
    ("pb", "padding-bottom"),
    ("pl", "padding-left"),
    ("px", "padding-left padding-right"),
    ("py", "padding-top padding-bottom"),
];
